upstream venus_frontend {
    server frontend:3000;
}

upstream venus_api_gateway {
    server api-gateway:4000;
}

server {
    listen 80;
    server_name _;

    location /api/ {
        proxy_pass http://venus_api_gateway;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass http://venus_frontend;
    }
}
